<?php
/**
 * Created by PhpStorm.
 * @user: MackRais
 * @site: http://mackrais.com
 * @email: mackraiscms@gmail.com
 */

namespace mackrais\portfolio\controllers;

use LinkedIn\AccessToken;
use mackrais\portfolio\services\LinkedInOAuth;
use Yii;
use yii\helpers\Html;
use yii\helpers\Url;
use yii\web\Controller;
use LinkedIn\Client;
use LinkedIn\Scope;



/**
 * Class DefaultController
 * @package app\modules\sitemap\controllers
 */
class DefaultController extends Controller
{
    private LinkedInOAuth $linkedInOAuth;

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        $this->linkedInOAuth = new LinkedInOAuth(
            '86stm6706xvgwr',
            '7bQZZOTg1HFEL0PO',
            'http://mackrais.loc/portfolio/linkedin-oauth'
        );
        
    }

    /**
     *
     */
    public function actionIndex(){


//        echo Html::a('login', $this->linkedInOAuth->getLoginUrl());


        return $this->render($this->action->id . '.php', []);
    }

    public function actionLinkedinOauth(){
        $code = Yii::$app->request->queryParams['code'] ?? null;

        $accessToken = $this->linkedInOAuth->getClient()->getAccessToken($code);


        file_put_contents('token.json', json_encode($accessToken));
    }

    public function actionSkills(){
        // load token from the file
        $tokenString = file_get_contents('token.json');
        $tokenData = json_decode($tokenString, true);
        $accessToken = new AccessToken($tokenData['token'], $tokenData['expiresAt']);

        $client = $this->linkedInOAuth->getClient();

// set token for client
        $client->setAccessToken($accessToken);

        $profile = $client->get(
            'me',
        );

        echo '<pre>';
        $skills = $client->get(
            'skills/' . $profile['id'],
            ['locale.language' => 'en', 'locale.country' => 'US']
        );


        print_r($profile);
        print_r($profile);
    }

    public function actionDownloadPdf(){
       echo '<pre>';

        $html = file_get_contents('http://mackrais.loc/portfolio/');
        $mpdf = new \Mpdf\Mpdf(['mode' => 'utf-8', 'format' => 'A4-L']);


        $doc = new \DOMDocument();
        libxml_use_internal_errors(true);
        $doc->loadHTML($html);

        $body = $doc->getElementsByTagName('body');
        $head = $doc->getElementsByTagName('head');
        $links = $doc->getElementsByTagName('link');
        $css = '';


        $css .= file_get_contents(__DIR__ . '/../assets/css/pdf.bootstrap4.css');
        $css .= file_get_contents(__DIR__ . '/../assets/css/portfolio.css');
        $css .= file_get_contents(__DIR__ . '/../assets/css/pdf.css');

        $body = $body->item(0);

        $mpdf->WriteHTML($css,\Mpdf\HTMLParserMode::HEADER_CSS);
        $mpdf->WriteHTML($doc->savehtml($body));
        $mpdf->Output();
        die;

        print_r($html);
        die;
    }
}
