<?php
/**
 * Created by PhpStorm.
 * @user: MackRais
 * @site: http://mackrais.com
 * @email: mackraiscms@gmail.com
 */

namespace mackrais\portfolio;

use yii\base\BootstrapInterface;
use yii\web\Application;

class Module extends \yii\base\Module implements BootstrapInterface
{
    public function bootstrap($app)
    {
//        if ($app instanceof \yii\console\Application) {
//            $this->controllerNamespace = 'app\modules\sitemap\commands';
//        }
        if ($app instanceof Application) {
            $this->intWebControllerMap();
        }
    }

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        $this->intWebControllerMap();
    }

    protected function intWebControllerMap()
    {
        $this->controllerMap = [
            'default' => __NAMESPACE__ . '\controllers\DefaultController',
            'administration' => __NAMESPACE__ . '\controllers\AdministrationController',
        ];
    }

    public function beforeAction($action)
    {
        $parent =  parent::beforeAction($action);
        $this->viewPath = __DIR__ . '/views/';
        $this->layout  = 'portfolioDefaultLayout';
        return $parent;
    }
}


